

class NotFoundError(ValueError):
    pass


class ExistsError(ValueError):
    pass
