http_exceptions/__init__.py,sha256=ApHxGdHjUu5_doWFp3Mg_XLoaA8mufc7PNmLdby4zrk,2489
http_exceptions/client_exceptions.py,sha256=ybiZl9xkZ7ljbetKf05RReyIEPVHZfFcZ85lYh9hPnk,9462
http_exceptions/http_exception.py,sha256=Q5IMWlpZUZD5ktNpKysWQzbHQtcyKtra_WNVtjsPKvQ,2231
http_exceptions/py.typed,sha256=dHaMYeog-n6iNI7LusnkAs74dFFA91AqOP7_KoQtpik,54
http_exceptions/server_exceptions.py,sha256=CsDRPZreIkZ70pBkvYsN7UDrCwWO2GmZkwIHHVzxm0Y,3849
http_exceptions-0.1.1.dist-info/METADATA,sha256=_NTyJBLF4js-mVn66DQ6WyMi649pUvapvjWdZQe1v_8,3430
http_exceptions-0.1.1.dist-info/WHEEL,sha256=ewwEueio1C2XeHTvT17n8dZUJgOvyCWCt0WVNLClP9o,92
http_exceptions-0.1.1.dist-info/top_level.txt,sha256=nCsOu8w0eKykZ5L75RPpbMclcCQvAnVxrTtT26W_xiM,16
http_exceptions-0.1.1.dist-info/RECORD,,
